### PR TITLE
Refactoring SCPI-Parser

### PR DESCRIPTION
**Pull request by Metaln00b**
- Adding example using an ethernet shield v2 (W5500) in combination with
a DHT-22 temperature and humidity sensor
- Removing compiler warnings
- Clean up library code
- Using serial interface as debug interface
- Now responds to non-existing commands
- Token changed to '\r', because of '\r\n'
- Works with puTTY telnet (Implicit CR in every LF, Telnet negotation
mode Passive)
- Works with labVIEW (Stop reading after linefeed and remove CRLF)

### CODE REVIEW

**Comment by Metaln00b** [comment]
Please look at the library code, maybe my version of your scpi parser will only work with ethernet.

**Comment by Vrekrer** [comment]
Wow, that is a lot of work. Thanks.

But there are some issues:

I think the  "example" including temperature and humidity sensor is too complicated to be a library example. For me that is a project using this library and should be listed here https://github.com/Vrekrer/Vrekrer_scpi_parser/issues/5

What do you mean by:
- Using serial interface as debug interface
- Now responds to non-existing commands
?


By "Clean up library code", did you mean change the code style?
I don't have much time now, but I am still the maintainer of this library and I like the Google C++ style.
But if you implement a hash function instead of my "base SCPI_MAX_TOKENS" for GetCommandCode then I let you choose any code style you want.

Can you make small, split commits / pull requests?  So I can accept the really good parts (like "Removing compiler warnings") and discuss or review the others.

**Comment by Metaln00b** [comment]
What do you mean by:

Using serial interface as debug interface

- I mean, that the ethernet is receiving the command and the serial interface is sending information, which command was entered and a lot debug stuff.

Now responds to non-existing commands
?

- That means if a command was entered which does not exist, the response will be "Command not found".

I will make all changes to a seperate commits, later.

**Comment by Vrekrer** [comment]
Compiler warnings are now fixed https://github.com/Vrekrer/Vrekrer_scpi_parser/commit/a8bf670cc8cc964e318b512f59e279e0eae9e052 and some spelling too https://github.com/Vrekrer/Vrekrer_scpi_parser/commit/8e5ede806114c4698f61084b1a448e32b8a05828
Closing this pull request

**Pull request closed without merging**
